// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1I6J9dq7UKIElyY5rufeF1c-q-FR2LM0',
    appId: '1:347217087668:web:0ae4860fc19031f624dbe1',
    messagingSenderId: '347217087668',
    projectId: 'jomimpactdb',
    authDomain: 'jomimpactdb.firebaseapp.com',
    storageBucket: 'jomimpactdb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7n7FOkTY5pVHqdonyho4Tp185nHWtA4c',
    appId: '1:347217087668:android:fe7f4255dcc6f40924dbe1',
    messagingSenderId: '347217087668',
    projectId: 'jomimpactdb',
    storageBucket: 'jomimpactdb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEMpzWo0rQzRp1O8uTrzHug0yob50ejqc',
    appId: '1:347217087668:ios:8d6c45924d95110224dbe1',
    messagingSenderId: '347217087668',
    projectId: 'jomimpactdb',
    storageBucket: 'jomimpactdb.firebasestorage.app',
    iosBundleId: 'com.example.jomimpact',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEMpzWo0rQzRp1O8uTrzHug0yob50ejqc',
    appId: '1:347217087668:ios:8d6c45924d95110224dbe1',
    messagingSenderId: '347217087668',
    projectId: 'jomimpactdb',
    storageBucket: 'jomimpactdb.firebasestorage.app',
    iosBundleId: 'com.example.jomimpact',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1I6J9dq7UKIElyY5rufeF1c-q-FR2LM0',
    appId: '1:347217087668:web:e2bb3ac9c634f26524dbe1',
    messagingSenderId: '347217087668',
    projectId: 'jomimpactdb',
    authDomain: 'jomimpactdb.firebaseapp.com',
    storageBucket: 'jomimpactdb.firebasestorage.app',
  );

}